// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbeoejuivhurmprizzwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZW9lanVpdmh1cm1wcml6endvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4Njc1MzcsImV4cCI6MjA3MTQ0MzUzN30.VLlkxtL_iPBYhghAbS336JWruS2KC2FTBddoGDu6zvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});